spring.application.name=fleet-service
server.port=8081

# MongoDB Connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Security - MUST Match Auth Service Key
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}